[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@chainlink/=lib/chainlink-brownie-contracts/contracts/src/v0.8/",
    "@solmate/=lib/solmate/src/",
    "@foundry-devops/=lib/foundry-devops/src/"
    ]

[fs_permissions]
read = ["./broadcast"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options